### ISSUE TITLE
[Error] Problem Event Name:	CLR20r3

### ISSUE THREAD

**Issue by thefinalwolf** [mztikk/AoBSigmaker#1]
Hello,
Just a heads up. I grabbed your program as soon as you updated today and I've been trying to get it to work for a while.

I'm experiencing an issue with the x64 version of the program. I made sure to update my .net framework as well.
I'm still in the process of changing settings around and searching Google for the error code, so I'll close the issue if I determine it's something on my machine.
~~Haven't tried x86 version yet, but will do so soon.~~ Same error with x86.

`Problem signature:`
  `Problem Event Name:	CLR20r3`
  `Problem Signature 01:	AoBSigmaker_x64.exe`
  `Problem Signature 02:	1.1.0.0`
 ` Problem Signature 03:	59ff5eaa`
  `Problem Signature 04:	mscorlib`
  `Problem Signature 05:	4.7.2558.0`
  `Problem Signature 06:	59d41393`
  `Problem Signature 07:	426d`
  `Problem Signature 08:	a4`
  `Problem Signature 09:	System.Windows.Markup.XamlParse`
  `OS Version:	6.1.7601.2.1.0.256.1`
  `Locale ID:	1033`
  `Additional Information 1:	4f2e`
  `Additional Information 2:	4f2ebe18a3c6c4bda02620df9330fe02`
  `Additional Information 3:	78e3`
  `Additional Information 4:	78e30c73e3d30ee76db6dec22514f902`

**Comment by mztikk** [comment]
You get this on startup? Program doesnt even load?
What windows version are you using?

**Comment by thefinalwolf** [comment]
Sorry for delay in replay.
Yes, I was using Win7 and the releases.

I've tested and confirmed that the latest releases (both x64 and x86) work just fine now. 
Looks really slick!
